server:
  port: 3000
spring:
  datasource:
    url: jdbc:mysql://121.36.19.182:3306/studyroom?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: nbuuser
    password: Nbucs123..
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
jwt:
  secret: 0QyIfFneqZvORpvsP1659fzv9Jq6y15ckYx4Ei4uXI/pj58dbmMJ3M2upJepbBaHQwzOU641eWiHDpXVPcSnCA==
  expiration: 86400000