spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studyroom?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: yzj225315,.
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false